In [6]:
def genInt(x):
    return int(x)

a = genInt('10')
print(a, type(a)) # type : 이 클래스를 누가 만들었나, 어느 그룹에 속하는가 / type check => X
# Class / Field / Space

10 <class 'int'>


In [8]:
import numpy as np

a = np.linspace(1,10,10)

print(-a)
print(np.fabs(-a))
print(type(np.fabs)) # universal function은 for문이 내장되어 있음
s = np.sign(-a) 
print(s)



[ -1.  -2.  -3.  -4.  -5.  -6.  -7.  -8.  -9. -10.]
[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
<class 'numpy.ufunc'>
[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
