In [2]:
#Matrix Class
# NDARRAY와 MATRIX구분
# matrix는 Mathlab기능 지원
# ndarray : 다차원, matrix : 2차원
# * 연산자 - ndarray : 요소간 곱, matrix : 행렬곱
# Matrix는 dot/* 처리가 동일, ndarray는 */muliply 가 동일

import numpy as np
m1 = np.matrix([1,2,3,4])
#print(m1*m1)
print(m1*m1.T) # .T => Transpose
print(m1.dot(m1.T))
print(np.multiply(m1,m1))

a1 = np.array([1,2,3,4])
print(a1*a1.T)
print(a1.dot(a1.T))
print(np.multiply(a1,a1))

[[30]]
[[30]]
[[ 1  4  9 16]]
[ 1  4  9 16]
30
[ 1  4  9 16]


In [16]:
# Matrix 덧셈/뺄셈
# 행렬끼리 shape가 같으면 덧셈과 뺄셈 가능
A = np.array([[1,2],[3,4]])
print(np.shape(A))
B = np.array([[4,3],[2,1]])
print(np.shape(B))
print(A)
print(B)
print(A+B)
print(A-B)

(2, 2)
(2, 2)
[[1 2]
 [3 4]]
[[4 3]
 [2 1]]
[[5 5]
 [5 5]]
[[-3 -1]
 [ 1  3]]


In [13]:
# Matrix 곱셈 / 나눗셈
A = np.array([[1,2],[3,4]])
print(np.shape(A))
B = np.array([[4,3],[2,1]])
print(np.shape(B))
print(A)
print(B)
print(A*B)
print(A/B)
# truedivide
# floordivide (소수점 버림)
dir(int)
dir(float)
5.3//3.2
5.3.__floordiv__(3.2)
#5.__ceil__(3)
dir(int)
int.__bases__ # 상속받은 class display

(2, 2)
(2, 2)
[[1 2]
 [3 4]]
[[4 3]
 [2 1]]
[[4 6]
 [6 4]]
[[ 0.25        0.66666667]
 [ 1.5         4.        ]]


(object,)

In [27]:
# Matrix Dot
# ndarray 타입으로 리턴
A = np.array([[1,2],[3,4]])
B = np.array([[4,3],[2,1]])

print(A)
print(B)
print(A.dot(B))
print(type(A.dot(B)))

[[1 2]
 [3 4]]
[[4 3]
 [2 1]]
[[ 8  5]
 [20 13]]
<type 'numpy.ndarray'>


In [3]:
# Dot 연산 : ndarray(4,3) * (3,1) => (4,1)
persons=np.array([[100,175,210],[90,160,150],[200,50,100],[120,0,310]])
print("shape of persons : ", persons.shape)
price_per_100g = np.array([2.98,3.90,1.99])
print(price_per_100g.shape)
price_in_cent = np.dot(persons,price_per_100g)
print(price_in_cent, type(price_in_cent), price_in_cent.shape)

#price_in_cent = np.dot(persons[2],price_per_100g)
#print(price_in_cent, type(price_in_cent))
price_in_euro=price_in_cent/np.array([100,100,100,100])
print(price_in_euro)
# print
# 2.X : python 키워드 => 괄호를 하든 안하든 상관 없음
# 3.X : function

('shape of persons : ', (4, 3))
(3,)
(array([ 1398.4,  1190.7,   990. ,   974.5]), <type 'numpy.ndarray'>, (4,))
[ 13.984  11.907   9.9     9.745]


In [9]:
# Matrix타입 : 연산(*)은 dot과 동일
xm = np.matrix(((2,3),(3,5)))
ym = np.matrix(((1,2),(5,-1)))
print(xm)
print(xm*ym)
print(type(xm))

[[2 3]
 [3 5]]
[[17  1]
 [28  1]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [12]:
# Matrix 연산(*) : asmatrix
# Matrix타입과 ndarray간의 연산을 할 경우 ndarray -> matrix로 전환후 연산처리
xm = np.matrix(((2,3),(3,5)))
xa = np.array(((2,3),(3,5)))
print(np.mat(xa)*xm) # mat => type casting이 아니고 새로운 객체를 만듬
print(np.asmatrix(xa)*xm)

[[13 21]
 [21 34]]
[[13 21]
 [21 34]]


In [14]:
# numpy dtype class
# dtype class 이해하기
# encoding (bit -> byte -> text)
# MS 코덱 : CP949
# byte -> text : decode , text -> byte : encode
# python 2 : byte(ascii) 기본
# python 3 : text(unicode) 기본 (한글 :  조합형/ 완성형)
# 메모리 처리방식
# Little-endian / Big-endian
# little : 좌측부터, Big : 우측부터 저장
# itemsize 메소드는 저장되는 메모리의 크기를 지정
# littel-endian은 좌측, big-endian은 우츨부터 저장
# numpy의 배열은 flat으로 관리하고 view만 배열형태로 보여줌
ar = np.array([1,2,3],dtype='<i4')
print(ar.tostring())

l = ar.tostring()
print(ar.itemsize)

print(l[0:8])


ar = np.array([1,2,3],dtype='>i4')
print(ar.tostring())
print(ar.dtype)

bytes(1)

b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'
4
b'\x01\x00\x00\x00\x02\x00\x00\x00'
b'\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03'
>i4


b'\x00'

In [15]:
# not-relevant : endian에 상관없이 문자를 저장할 때 제일 왼쪽부터 저장
sr = np.array(['a','b',"abc"],dtype='|S4')
print(sr.tostring())
print(sr.dtype)
print(sr.tostring()[0:10])#abab

b'a\x00\x00\x00b\x00\x00\x00abc\x00'
|S4
b'a\x00\x00\x00b\x00\x00\x00ab'


In [19]:
# 데이터타입 이해하기
# bool -> int, float->int 로 전환
B = np.array([[142,56,189,65],
             [299,288,10,12],
             [55,142,17,18]])
print(B>=82)

b = B>82
print(b)
c = b.astype(np.int)
print(c)


ar = np.array([1.3,2.7,3.5],dtype='<i4')
print(ar.astype(np.int)) # astype : 현재 type을 바꾸겠다.
bool.__bases__
True+1
10*False
# 상품 추천때 활용

[[ True False  True False]
 [ True  True False False]
 [False  True False False]]
[[ True False  True False]
 [ True  True False False]
 [False  True False False]]
[[1 0 1 0]
 [1 1 0 0]
 [0 1 0 0]]
[1 2 3]


0

In [37]:
# int / float / bool_ 생성
# numpy 내의 데이터 타입은 ndarray생성자로 사용
y = np.int16([1,2,3])
print(y)
print(type(y))

x = np.float32([1,2])
print(x)
print(type(x))

ba = np.array([True,False,True],dtype=np.bool)
print(ba,type(ba))

b = np.bool_([True,False,True])
print(b,type(b))

print(b.__class__.mro())#?

[1 2 3]
<type 'numpy.ndarray'>
[ 1.  2.]
<type 'numpy.ndarray'>
(array([ True, False,  True], dtype=bool), <type 'numpy.ndarray'>)
(array([ True, False,  True], dtype=bool), <type 'numpy.ndarray'>)
[<type 'numpy.ndarray'>, <type 'object'>]


In [42]:
# numpy.dtype
# numpy.dtype 생성자
# numpy.dtype은 ndarray 생성에 필요한 데이터 타입을 정의하기 위한 클래스
# numpy.dtype(object,align=False,copy=False)
dt = np.dtype(np.int16) # (np.int16, np.float64, np.string) => tuple 형태로 여러 형태를 넣을 수 있음
print(dt)
s = np.array(10,dtype=dt)
print(s)
s1 = np.array([1,2,3],dtype=dt)
print(s1)

int16
10
[1 2 3]


In [49]:
# numpy.dtype 생성 예시
# Array 원소가 하나의 타입만 새팅할 수도 있고, 여러개의 데이터 타입을 구성할 수 있음
# Structured type : one field
dt = np.dtype([('f0','<i8')])# tuple형태로 type을 두개를 넣음
print(dt)
data1 = np.zeros((3,2),dtype=dt)
print(data1)
print(data1.dtype)

# Structured type : two field
data = np.zeros((3,2),dtype="int, int")
print(data)
print(data.dtype)#[('f0', '<i4'), ('f1', '<i4')] ?

dt = np.dtype([('f0','<i8'),('f1','<i8')])
data1 = np.zeros((3,2), dtype=dt)
print(data1)
print(data1.dtype)

[('f0', '<i8')]
[[(0,) (0,)]
 [(0,) (0,)]
 [(0,) (0,)]]
[('f0', '<i8')]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]
[('f0', '<i4'), ('f1', '<i4')]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]
[('f0', '<i8'), ('f1', '<i8')]


In [59]:
# numpy.dtype 변수
# dtype 변수 -1
f_ = np.array([1.0,2.0,3.0]) # class 생성됨 =>  속성이 있다. => .연산으로 접근
print(type(f_))
print(f_,f_.itemsize) #요소들의 크기
print(f_.dtype.char) # 타입 표시
print(f_.dtype.names) # ordered list field명 없으면 None ?
print(f_.dtype.name) # 현재 타입 명
print(f_.dtype.shape)
print(f_.dtype.num) # builtin 타입의 순서 ?

<type 'numpy.ndarray'>
(array([ 1.,  2.,  3.]), 8)
d
None
float64
()
12


In [67]:
# dtype 변수 -2
f = np.array([1.0,2.0,3.0])
print(f_.dtype.type) # numpy 내의 타입으로 표시
print(f_.dtype.str) # Array-protocol type string 표시, <:little-endian으로 float 8개 바이트 처리
print(f_.dtype.isbuiltin) # 1: numpy 내부 타입, 2: 사용자 정의 타입
print(f_.dtype.byteorder)# =:기본, <:little, >:big, |:not applicable
print(f_.dtype.alignment)# 타입 내 요소들의  구성 크기
print(f_.dtype.isalignedstruct) # ?

<type 'numpy.float64'>
<f8
1
=
8
False


In [79]:
# dtype 변수 - 3
f_ = np.array([1.0,2.0,3.0])
print(f_.dtype.descr) # Array interface 표시
print(f_.dtype.hasobject)# any reference-counted objects in any fields or sub-dtype 존재시  True
print(f_.dtype.subdtype)
print(f_.dtype.base)# 기본 정의된 타입
print(f_.dtype.kind)# array-protocol type
print(f_.dtype.isnative)# python 내부 byte order 사용 여부
print(f_.dtype.flags)# interpret 되어진 bit flags
print(f_.dtype.fields)# Dtype 정의한 fields
print(f_.dtype.metadata)

[('', '<f8')]
False
None
float64
f
True
0
None
None


In [87]:
# dtype class column 이름 부여하기
# DTYPE 구조
# ndarray 내부 원소에 이름 부여
# 컬럼별 처리를 위해 index이외의 이름을 부여하여 직접 접근

xz = np.linspace(1,10,5,dtype=[('x',np.int32)]) # 컬럼이름부여
print(xz)
print(xz.ndim)
print(xz.shape)
print(xz.dtype)
print(xz['x']) # 컬럼이름으로 값 출력

xz['x'].fill(10)
print(xz)

[( 1,) ( 3,) ( 5,) ( 7,) (10,)]
1
(5,)
[('x', '<i4')]
[ 1  3  5  7 10]
[(10,) (10,) (10,) (10,) (10,)]


In [101]:
# dtype에 컬럼명 정의 : tuple
# dtype 정의 시 컬럼명, 컬럼값을 튜클로 정의하면 컬럼명으로 접근가능
dt = np.dtype([('a',np.str_,10),('b',np.float64)])
print(dt['a'])
print(dt['b'])

a = np.array([('aaa',10000)],dtype = dt)
print(a)
print(a['a']) # ?
print(a['b']) # ?

dt = np.dtype([('a','S10'),('b','f8')])
print(dt['a'])
print(dt['b'])
print(dt)

a = np.array(('aaa',10000),dtype=dt)
print(a)
a = np.array([('aaa',10000)],dtype=dt)
print(a)
print(a['a']) # ?
print(a['b'])

|S10
float64
[('aaa',  10000.)]
['aaa']
[ 10000.]
|S10
float64
[('a', 'S10'), ('b', '<f8')]
('aaa',  10000.)
[('aaa',  10000.)]
['aaa']
[ 10000.]


In [110]:
#dtype에 컬럼명 정의 : dict
# dict내에 names에 컬럼명 정의, formats에 타입 또는 컬럼명과 타입으로 정의
# list[(key, value),(key, value)] => dict로 변환 가능

dict_type = {'names':['col1','col2','col3'], 'formats':[np.int_, np.float_,np.float_]}

a = np.zeros(4,dtype=dict_type)
print(a)
print(a.dtype)
a['col1'] = (10,22.3,44.5,22.1)
print(a)

dict_type1 = {'surname':('S25',0),'age':(np.uint8,25)}

b = np.array([("dahl",20),("park",30)],dtype=dict_type1)
print(b)
print(b["surname"])

[(0,  0.,  0.) (0,  0.,  0.) (0,  0.,  0.) (0,  0.,  0.)]
[('col1', '<i4'), ('col2', '<f8'), ('col3', '<f8')]
[(10,  0.,  0.) (22,  0.,  0.) (44,  0.,  0.) (22,  0.,  0.)]
[('dahl', 20) ('park', 30)]
['dahl' 'park']


In [119]:
# dtype에 컬럼명 정의 : 배열처리
# ndarray 생성 시 내부에 (int, float)를 원소로 한 2차원 배열이 생성됨
xz = np.zeros((2,2),dtype=[('x',np.int32),('y',np.float32)])
print(xz)
print(xz.ndim)
print(xz.shape)
print(xz.dtype)
print(xz['x'])
print(xz['y'])

xz['x'].fill(10)
print(xz)

[[(0,  0.) (0,  0.)]
 [(0,  0.) (0,  0.)]]
2
(2, 2)
[('x', '<i4'), ('y', '<f4')]
[[0 0]
 [0 0]]
[[ 0.  0.]
 [ 0.  0.]]
[[(10,  0.) (10,  0.)]
 [(10,  0.) (10,  0.)]]


In [22]:
# 컬럼명 변경
# dtype내의 names 변수로 컬럼을 조회 및 갱신 가능

x = np.zeros(3, dtype={'col1':('i1',1,'title 1'),'col2':('f4',0,'title 2')}) # 중간에 숫자 0, 1 ?

print(x.dtype.names) 
print(x['col1'])
x.dtype.names = ('X','Y')
print(x.dtype.names)

('col2', 'col1')
[0 0 0]
('X', 'Y')


In [142]:
# 컬럼명으로 접근/변경
# numpy.array생성시 sequence각 요소에 대해 접근변수와 타입을 정할 수 있음
x = np.array([(1,2.,'Hello'),(2,3.,'world')],
            dtype=[('foo','i4'),('bar','f4'),('baz','S10')])
# 요소 순서대로 int, float, string
print(x)
print(x.shape)

print(x[0])
print(x[0]['foo'])
print(x[0]['bar'])
print(x[0]['baz'])

print(x['foo'])
print(x['bar'])
print(x['baz'])

[(1,  2., 'Hello') (2,  3., 'world')]
(2,)
(1,  2., 'Hello')
1
2.0
Hello
[1 2]
[ 2.  3.]
['Hello' 'world']


In [153]:
# 컬럼명 접근 : fancy
# numpy.array를 여러 컬럼단위로 접근시는 실제 컬럼명을 리스트에 넣어서 검색

x = np.array([(1.5,2.5,(1.0,2.0)),(3.,4.,(4.,5.)),(1.,3.,(2.,6.))],
             dtype=[('x','f4'),('y',np.float32),('value','f4',(2,2))])
print(x) # ?
print(x[['x','y']]) # ? 왜 []가 두개씩?

print(x[['x','value']])

[( 1.5,  2.5, [[ 1.,  2.], [ 1.,  2.]])
 ( 3. ,  4. , [[ 4.,  5.], [ 4.,  5.]])
 ( 1. ,  3. , [[ 2.,  6.], [ 2.,  6.]])]
[( 1.5,  2.5) ( 3. ,  4. ) ( 1. ,  3. )]
[( 1.5, [[ 1.,  2.], [ 1.,  2.]]) ( 3. , [[ 4.,  5.], [ 4.,  5.]])
 ( 1. , [[ 2.,  6.], [ 2.,  6.]])]


In [158]:
# 컬럼명으로 변경
# numpy.array 생성시 sequence 각 요소에 대해 접근 변수에 대한 값을 변경할 수 있음
x = np.array([(1,2.,'Hello'),(2,3.,'world')],
            dtype=[('foo','i4'),('bar','f4'),('baz','S10')])
# 요소 순서대로 int, float, string
print(x)
print(x['foo'])
y = x['foo']
print(y) # [1 2] ?
y[:] = 2*y
print(y)
print(x['foo'])

[(1,  2., 'Hello') (2,  3., 'world')]
[1 2]
[1 2]
[2 4]
[2 4]
