In [1]:
# shape 조정함수
# Flatten/ravel 메소드의 차이
# Flatten메소는 하나의 별도의 새로운 객체를 만들기 위해 copy 연산을 사용
# ravel은 view만 제공하므로 변경하면 기존 ndarray가 갱신

import numpy as np
y = np.array(((1,2,3),(4,5,6),(7,8,9)))

s = y.flatten()

print(s)
print(y)

t=y.ravel()
t[0] = 100
print(t)
print(y)

# order : 다차원에서 flat으로 처리 시 order로 c언어 타입과 
# fortran언어 타입으로 표현 가능
y = np.array(((1,2,3),(4,5,6),(7,8,9)))

s = y.flatten(order='C')
print(s)
t = y.flatten(order = 'F')
print(t)
# flatten : 원본 안바뀜
# ravel : 원본 바꿈
sr = y.ravel(order='C')
print(sr)
tr = y.ravel(order='F')
print(tr)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[100   2   3   4   5   6   7   8   9]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]
[1 2 3 4 5 6 7 8 9]
[1 4 7 2 5 8 3 6 9]
[1 2 3 4 5 6 7 8 9]
[1 4 7 2 5 8 3 6 9]


In [14]:
# reshape 함수
# reshape(array-like, newshape(int, tuple), order='C')

X = np.array(range(24))
Y = X.reshape((3,4,2))
print(Y)
Z = np.reshape(Y,(2,6,2))
print(Z)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [16]:
# concatenate 함수 : 1차원
# concatenate((a1,a2,...),axis=0)로 array연결

x = np.array([11,22])
y = np.array([8,5,19])
z = np.array([1,3,5])
c = np.concatenate((x,y,z))
print(c)

[11 22  8  5 19  1  3  5]


In [19]:
# concatenate 함수 : n차원
x = np.array(range(12))
x = x.reshape((2,3,2))
y = np.array(range(100,112))
y = y.reshape((2,3,2))
z = np.concatenate((x,y))
print(z)

[[[  0   1]
  [  2   3]
  [  4   5]]

 [[  6   7]
  [  8   9]
  [ 10  11]]

 [[100 101]
  [102 103]
  [104 105]]

 [[106 107]
  [108 109]
  [110 111]]]


In [24]:
# np.newaxis 변수
# slice 처리와 같이 사용해서 축을 바꿈
# 1행 배열은 1열 배열로, 2열 3열 배열은 3행 2열 배열로 변환
x = np.array([2,5,18,14,4])
y = x[:,np.newaxis]
print(y)
x = np.arange(6)
y = x.reshape(2,3)
print(y)
print(y.shape)
print(y[:,np.newaxis]) # ? (2,3,1)
print(y.shape)

[[ 2]
 [ 5]
 [18]
 [14]
 [ 4]]
[[0 1 2]
 [3 4 5]]
(2, 3)
[[[0 1 2]]

 [[3 4 5]]]
(2, 3)


In [28]:
# tile
# A 배열에 대한 Reps는 axis에 따른 반복을 표시
# numpy.tile(A,reps)
# Reps가 scalar : 배수 만큼 증가
# Reps가 vector : 행과 열의 배수 만큼 증가
# Array_like를 ndarray로 변환
# Tile함수를 이요해서 array_like모형에 따라 ndarray로 변환
a = [1,2,3]
b = np.tile(a,2)
print(b)
b = np.tile(a,(2,1))
print(b)
b = np.tile(a,(2,2))
print(b)

[1 2 3 1 2 3]
[[1 2 3]
 [1 2 3]]
[[1 2 3 1 2 3]
 [1 2 3 1 2 3]]


In [36]:
# row/column stack 함수 : 1
# row_stack : row 단위 통합
# column_stack : column 단위 통합
A = np.array([3,4,5])
B = np.array([1,9,0])
print(np.shape(A))
print(np.row_stack((A,B)))
print(np.column_stack((A,B)))
print(np.shape(A))

(3,)
[[3 4 5]
 [1 9 0]]
[[3 1]
 [4 9]
 [5 0]]
(3,)


In [43]:
# row/column stack 함수 2
# Column_stack : 행은 그대로이고 열에 추가
# Row_stack : 열은 그대로이고 행에 추가

A = np.array([[3,4,5],
             [1,9,0],
             [4,6,8]])

print(A.shape)
print(np.column_stack((A,A)).shape)
print(np.column_stack((A,A)))
print(np.row_stack((A,A)).shape)
print(np.row_stack((A,A)))

(3, 3)
(3, 6)
[[3 4 5 3 4 5]
 [1 9 0 1 9 0]
 [4 6 8 4 6 8]]
(6, 3)
[[3 4 5]
 [1 9 0]
 [4 6 8]
 [3 4 5]
 [1 9 0]
 [4 6 8]]


In [49]:
# nonzero 확인 함수
# nonzero : Return the indices of the elements that are non-zero.
# count_nonzero 함수 : 개수 확인 
# flatnonzero 함수 : index 식별
Z = np.array([[142,56,0,65],
             [0,288,10,12],
             [55,142,0,18]])
print(Z.nonzero()) # ??
z = Z[Z.nonzero()] # [142  56  65 288  10  12  55 142  18]
print(z)

print(np.count_nonzero(Z))
print(np.flatnonzero(Z))

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 3, 1, 2, 3, 0, 1, 3]))
[142  56  65 288  10  12  55 142  18]
9
[ 0  1  3  5  6  7  8  9 11]
