In [2]:
# Numpy axis 이해하기
# 배열 축 이해 : 2차원
# 0 은 열, 1은 행
import numpy as np

f = np.arange(0,6).reshape(2,3)
print(f)

# column
print(np.mean(f,axis=0))
# row
print(np.mean(f,axis=1))

[[0 1 2]
 [3 4 5]]
[ 1.5  2.5  3.5]
[ 1.  4.]


In [7]:
# 배열 전치
# 데이터를 복사하지 않고 데이터 모양이 바뀐 뷰를 반환하는 기능
f = np.arange(0,12).reshape(3,4)
print(f)
print(f.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [12]:
# axis : 3차원
# 0은 두개의 행렬에서 각 열원소별로, 1은 행끼리 처리, 2는 내부 원소끼리 처리
# vector는 vector단위만 삭제 가능 , 원소 하나 삭제는 불가
f = np.arange(0,8).reshape(2,2,2)
print(f)

# [[0 1] + [4 5], [2 3] + [6 7]]
print(np.mean(f,axis=0))# ??
# [[0 1] + [2 3], [4 5] + [6 7]] 
print(np.mean(f,axis=1))# ??
# [[0+1 2+3],[4+5 6+7]]
print(np.mean(f,axis=2))# ??

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[ 2.  3.]
 [ 4.  5.]]
[[ 1.  2.]
 [ 5.  6.]]
[[ 0.5  2.5]
 [ 4.5  6.5]]


In [19]:
# 축변경 : transpose
# tuple로 축 번호를 받아 치환하지만 axis는 0,1이 default이므로
# 배열 전치를 하려면 1,0으로 축을 변경해야 함

f = np.arange(0,12).reshape(3,4)
print(f)
print(f.transpose((0,1)))
print(f.transpose((1,0)))

# 3차원 일때
f = np.arange(0,12).reshape(2,2,3)
print(f)
print(f.transpose((0,1,2)))
print(f.transpose((2,1,0))) # ?

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[ 0  6]
  [ 3  9]]

 [[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]]


In [36]:
# numpy 함수
# inner/outer 함수 이해하기
# A = [[1,0]], B = [[4,1]]
# numpy.inner(A,B)
# array([[1*4+0*1]])
a = np.array([[1,0]])
b = np.array([[4,1]])
print(a.shape, b.shape)
print(np.inner(a,b))

a1 = np.array([[1,0,3]])
b1 = np.array([[4,1,3]])
print(a1.shape, b1.shape)
print(np.inner(a1,b1))

va = np.array([[1,0]])
vb = np.array([[4,1]])
vc = np.array([[4],[1]])

print(np.dot(va,vc))
print(np.inner(va,vb))

((1, 2), (1, 2))
[[4]]
((1, 3), (1, 3))
[[13]]
[[4]]
[[4]]


In [39]:
# outer
# A = [[a1,b1]] , B = [[a2,b2]]
# numpy.outer(A,B)
# array([[a1*a2 , a1*b2][b1*a2, b1*b2]])
# 벡터의 내부 곱한것을 더해서 값을 표현
# 첫번째 벡터의 전치와 두번째 벡터와의 Dot연산과 같은 결과

a = np.array([[1,0]])
b = np.array([[4,1]])
print(a.shape, b.shape)
print(np.outer(a,b))
print(np.dot(a.T,b))


((1, 2), (1, 2))
[[4 1]
 [0 0]]
[[4 1]
 [0 0]]


In [5]:
# 숫자처리 함수
# 절대값/부호 처리
# abs, fabs : 각원소의 절대값을 구함, 복소수가 아닌 경우 fabs로 빠른 연산 처리
# sign : 부호에 대한 처리, 1은 양수, -1은 음수

a = np.linspace(1,10,10)
print(a)
print(np.fabs(-a)) # ?
print(-a)
print(np.fabs(-a))
print(type(np.fabs)) # universal function은 for문이 내장되어 있음 => vector 연산, broadcasting 
print(type(np.where))
s= np.sign(-a)
print(s)# 부호 보여주기
print(a*s)

print(np.ufunc.__bases__)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
[ -1.  -2.  -3.  -4.  -5.  -6.  -7.  -8.  -9. -10.]
[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
<class 'numpy.ufunc'>
<class 'builtin_function_or_method'>
[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
[ -1.  -2.  -3.  -4.  -5.  -6.  -7.  -8.  -9. -10.]
(<class 'object'>,)


In [53]:
# 지수와 로그 = > 역함수 관계
# exp는 지수 계산
# log, log10, log2, log1p는 자연로그 로그10, 로그2, 로그(1+x)

a = np.linspace(1,10,10)
print(np.exp(a))
print(np.log(a))
print(np.log10(a))
print(np.log2(a))
print(np.log1p(a))
print(np.log(1+a))

[  2.71828183e+00   7.38905610e+00   2.00855369e+01   5.45981500e+01
   1.48413159e+02   4.03428793e+02   1.09663316e+03   2.98095799e+03
   8.10308393e+03   2.20264658e+04]
[ 0.          0.69314718  1.09861229  1.38629436  1.60943791  1.79175947
  1.94591015  2.07944154  2.19722458  2.30258509]
[ 0.          0.30103     0.47712125  0.60205999  0.69897     0.77815125
  0.84509804  0.90308999  0.95424251  1.        ]
[ 0.          1.          1.5849625   2.          2.32192809  2.5849625
  2.80735492  3.          3.169925    3.32192809]
[ 0.69314718  1.09861229  1.38629436  1.60943791  1.79175947  1.94591015
  2.07944154  2.19722458  2.30258509  2.39789527]
[ 0.69314718  1.09861229  1.38629436  1.60943791  1.79175947  1.94591015
  2.07944154  2.19722458  2.30258509  2.39789527]


In [59]:
# 거듭제곱 / 제곱근
# square는 거듭제곱, sqrt는 제곱근, power는 두배열의 거듭제곱

a = np.linspace(1,10,10)
print(np.square(a))
print(np.sqrt(a))
#print(np.log(a))
print(np.power(a,3))

[   1.    4.    9.   16.   25.   36.   49.   64.   81.  100.]
[ 1.          1.41421356  1.73205081  2.          2.23606798  2.44948974
  2.64575131  2.82842712  3.          3.16227766]
[    1.     8.    27.    64.   125.   216.   343.   512.   729.  1000.]


In [64]:
# 절사 / 절상
# ceil : 각 원소의 값보다 같거나 큰 정수 중 가장 큰 정수 반환
# floor : 각 원소의 값보다 작거나 같은 정수 중 가장 작은 수 반환
# rint : 각 원소의 소수자리를 반올림하고 dtype유지
b = np.linspace(1,5,10)
print(b)
print(np.ceil(b))
print(np.floor(b))
print(np.rint(b))

[ 1.          1.44444444  1.88888889  2.33333333  2.77777778  3.22222222
  3.66666667  4.11111111  4.55555556  5.        ]
[ 1.  2.  2.  3.  3.  4.  4.  5.  5.  5.]
[ 1.  1.  1.  2.  2.  3.  3.  4.  4.  5.]
[ 1.  1.  2.  2.  3.  3.  4.  4.  5.  5.]


In [72]:
# 사칙연산 
# apply(함수, value, value) =>  함수에 type이 다른 value를 넣어 계산 시 type을 맞춰 줌 => 함수 대신 연산자 넣으면 Error => 함수넣음
a = np.linspace(1,10,10)
print(a)
print(np.add(a,a))
print(np.subtract(a,a)) 
print(a)
print(np.multiply(a,a))
print(np.divide(a,a))
print(np.floor_divide(a,a)) # //


[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
[   1.    4.    9.   16.   25.   36.   49.   64.   81.  100.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [80]:
# mode 연산
# modf : 단항연산으로 자신의 나머지와 몫 구하기
# mod : 이항연산으로 나머지만 구함
a = np.linspace(1,10,10)
print(a)
print(np.modf(a))# ?
print(np.mod(1+a,a))


[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
(array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]), array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.]))
[ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[False False False  True  True  True  True  True  True  True]


In [90]:
# 관계연산
# 두 배열간의 관계를 표시하거나 부울 표시된 결과에 대해 any/all로 전체 결과 확인

a = np.linspace(1,10,10)
print(np.equal(a,a))
print(np.not_equal(a,a))
# a > 3
b = np.greater(a,3)
print(b)
print(np.any(b)) # ?
print(np.all(b)) # ?
# a >= 3
c = np.greater_equal(a,3)
print(c)
# a < 3
d = np.less(a,3)
print(d)
#a <= 3
e = np.less_equal(a,3)
print(e)

[ True  True  True  True  True  True  True  True  True  True]
[False False False False False False False False False False]
[False False False  True  True  True  True  True  True  True]
True
False
[False False  True  True  True  True  True  True  True  True]
[ True  True False False False False False False False False]
[ True  True  True False False False False False False False]


In [10]:
# where 연산
# 조건을 표현한 배열을 기준으로 True일 경우 첫번째 배열의 요소,
# False일 경우는 두번째 배열의 요소로 처리

a = np.linspace(1,10,10)
print(a)
result = np.where(a>3,3,0)
print(result)

b = a>3
print(b)
result = np.where(b,a,0)
print(result)
result = np.where(b)
print(result)

# list comprehenstion
x = 10
x if x<0 else 0
print(x)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
[0 0 0 3 3 3 3 3 3 3]
[False False False  True  True  True  True  True  True  True]
[  0.   0.   0.   4.   5.   6.   7.   8.   9.  10.]
(array([3, 4, 5, 6, 7, 8, 9], dtype=int64),)
10


In [103]:
# HYPOT함수 => 피타고라스 정리
# sqrt(a제곱 + b제곱)
print(np.hypot(np.array([3]),np.array([4]))) 
print(np.hypot(3,4))

np.sqrt(3**2 + 4**2)

np.hypot(3*np.ones((3,3)),[4])

[ 5.]
5.0


array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

In [106]:
# 집합함수 => 상품 vector화 => 구매한 상품 구하기 
# unique / in1d
# 집합처럼 만드는 unique함수와 포함관계를 표시하는 in1d함수
y = np.array([1,2,3,4,5,1,2,3])

# 집합생성
A = np.unique(y)
print(A)
# 집합 내의 포함된 원소인지 확인
print(np.in1d([2,3,7],A))

[1 2 3 4 5]
[ True  True False]


In [117]:
# 집합연산하기 -> 일단 1차원적으로 변환해야 함
y = np.array([1,2,3,4,5,1,2,3])
z = np.array([1,2,3,1,2,3])

# 집합 생성
A = np.unique(y)
B = np.unique(z)

# 합집합, 교집합, 차집합, 대칭차집합
print(np.union1d(A,B))
print(np.intersect1d(A,B))
print(np.setdiff1d(A,B))
print(np.setdiff1d(B,A))
print(np.setxor1d(A,B))

y = np.array([[1,2,3,4],[5,1,2,3]])
z = np.array([[1,2,3],[1,2,3]])

# 집합 생성
A = np.unique(y)
B = np.unique(z)
print(A)
print(B)
print(np.union1d(A,B))
print(np.intersect1d(A,B))
print(np.setdiff1d(A,B))
print(np.setxor1d(A,B))

[1 2 3 4 5]
[1 2 3]
[4 5]
[]
[4 5]
[1 2 3 4 5]
[1 2 3]
[1 2 3 4 5]
[1 2 3]
[4 5]
[4 5]


In [126]:
# 통계함수
# 합/평균/분산/표준편차
# 평균 => 경향의 대표값
# cumsum / comprod는 각 원소의 값을 누적하는 함수
a = np.linspace(1,10,10)
print(a)
print(np.sum(a))
print(np.cumsum(a))
print(np.cumprod(a)) # ?
print(np.mean(a))
print(np.var(a)) # ?
print(np.std(a))

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
55.0
[  1.   3.   6.  10.  15.  21.  28.  36.  45.  55.]
[  1.00000000e+00   2.00000000e+00   6.00000000e+00   2.40000000e+01
   1.20000000e+02   7.20000000e+02   5.04000000e+03   4.03200000e+04
   3.62880000e+05   3.62880000e+06]
5.5
8.25
2.87228132327


In [135]:
# 최대/최소값

a = np.linspace(1,10,10)
b = a+1
print(np.min(a))
print(np.max(a))
print(np.minimum(a,b)) #?
print(np.maximum(a,b)) #?

arr = np.array([9,19,29,39,49])

print("index")
print(arr.argmax())
print(arr.argmin())

print("value")
print(arr[np.argmax(arr)]) # index 위치
print(arr[np.argmin(arr)])

1.0
10.0
[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.  11.]
index
4
0
value
49
9
