In [8]:
# numpy 검색/갱신
# 내부 원소 접근 방식
# __getitem__ 비교
# numpy.ndarray 타입에서는 __getitem__에 논리연산등 다양한 처리를 허용
import numpy as np
l = range(1,10)
print(type(l),l)
nparr = np.arange(1,10,dtype=np.float_)
print(type(nparr),nparr)

print(l.__getitem__(1))
arI = np.array([True, False, True, False, True, False, True, False, True, False])

print(arI, arI.dtype)
print(nparr.__getitem__(1))
print(nparr.__getitem__(arI))

(<type 'list'>, [1, 2, 3, 4, 5, 6, 7, 8, 9])
(<type 'numpy.ndarray'>, array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))
2
(array([ True, False,  True, False,  True, False,  True, False,  True, False], dtype=bool), dtype('bool'))
2.0
[ 1.  3.  5.  7.  9.]


c:\users\05-0604\python2\lib\site-packages\ipykernel_launcher.py:16: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 9 but corresponding boolean dimension is 10
  app.launch_new_instance()


In [13]:
# __setitem__
# index 와 slice 처리시 기존 리스트의 방식보다 더 다양한 처리를 위해 __setitem__메소드를 오버라이드 함
l = range(1,10)
print(type(l),l)
nparr = np.arange(1,10,dtype=np.float_)
print(type(nparr),nparr)

print(l.__getitem__(1))
arI = np.array([True, False, True, False, True, False, True, False, True, False])

print(arI, arI.dtype)
print(nparr.__getitem__(1))
print(nparr.__getitem__(arI))

print(l.__setitem__(1,100),l)
print(nparr.__setitem__(1,100),nparr)
print(nparr.__setitem__(arI,99),nparr) # true 인 것을 99로 set


(<type 'list'>, [1, 2, 3, 4, 5, 6, 7, 8, 9])
(<type 'numpy.ndarray'>, array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))
2
(array([ True, False,  True, False,  True, False,  True, False,  True, False], dtype=bool), dtype('bool'))
2.0
[ 1.  3.  5.  7.  9.]
(None, [1, 100, 3, 4, 5, 6, 7, 8, 9])
(None, array([   1.,  100.,    3.,    4.,    5.,    6.,    7.,    8.,    9.]))
(None, array([  99.,  100.,   99.,    4.,   99.,    6.,   99.,    8.,   99.]))


c:\users\05-0604\python2\lib\site-packages\ipykernel_launcher.py:13: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 9 but corresponding boolean dimension is 10
  del sys.path[0]
c:\users\05-0604\python2\lib\site-packages\ipykernel_launcher.py:17: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 9 but corresponding boolean dimension is 10


In [20]:
# 2차원 행과 열 접근
# 배열 접근하기 : 행과 열 구분
# 배열명[행 범위, 열범위] 행으로 접근, 열로 접근
l33 = [[1,2,3],[4,5,6],[7,8,9]]
np33 = np.array(l33,dtype=int)
print(np33.shape) #(3,3)
print(np33.ndim)
print(np33)

print("first row : ",np33[0])
print("first column : ",np33[:,0])

(3, 3)
2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
('first row : ', array([1, 2, 3]))
('first column : ', array([1, 4, 7]))


In [24]:
# 배열접근하기 : 행렬로 구분
# 첫번째와 두번째 행과 두번째와 세번째 열로 접근
l33 = [[1,2,3],[4,5,6],[7,8,9]]
np33 = np.array(l33,dtype=int)
print(np33)
print(np33[:2,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]


In [27]:
# 배열 접근하기 : 값
# 행과 열의 인덱스를 지정하면 실제 값에 접근해서 보여줌
l33 = [[1,2,3],[4,5,6],[7,8,9]]
np33 = np.array(l33,dtype=int)
print(np33)

print(np33[1,1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
5


In [30]:
# 배열 값 바꾸기 : Broadcasting
# 배열 계산시 scalar 값과 계산시 크기가 작은 것을 동일한 크기로 계산되도록 확산이 발생
l = [1,100,3,4,5,6,7]
npl = np.array(l,int)

npl[2:5] = 42
print(npl)

[  1 100  42  42  42   6   7]


In [36]:
# N차원 배열 처리
# 다차원 배열 : 열 조회/변경
# 7*4배열을 정의하고 첫번째 열의 값을 99로 변경
data1 = np.random.randn(7,4)
print(data1)
print("second column")
print(data1[:,1])

print("Updating second column")
data1[:,1] = 99
print(data1)

[[ 1.76367194 -0.5140513  -1.29135803 -1.9898328 ]
 [ 2.4966548  -0.09434927 -0.60729566  0.62656161]
 [ 1.10750792  0.01228651 -0.01096756 -0.29764366]
 [-1.2197574   1.32096754  0.06238085 -0.82019419]
 [ 0.10719297  0.73478831  0.12726238 -0.09699686]
 [-1.09134109 -0.26496879 -0.57327933 -0.82744862]
 [ 1.79708022  1.66288463  0.27927344 -0.54153934]]
second column
[-0.5140513  -0.09434927  0.01228651  1.32096754  0.73478831 -0.26496879
  1.66288463]
Updating second column
[[  1.76367194e+00   9.90000000e+01  -1.29135803e+00  -1.98983280e+00]
 [  2.49665480e+00   9.90000000e+01  -6.07295656e-01   6.26561608e-01]
 [  1.10750792e+00   9.90000000e+01  -1.09675630e-02  -2.97643657e-01]
 [ -1.21975740e+00   9.90000000e+01   6.23808521e-02  -8.20194194e-01]
 [  1.07192971e-01   9.90000000e+01   1.27262383e-01  -9.69968629e-02]
 [ -1.09134109e+00   9.90000000e+01  -5.73279334e-01  -8.27448625e-01]
 [  1.79708022e+00   9.90000000e+01   2.79273440e-01  -5.41539343e-01]]


In [39]:
# 비교연산 처리
f = np.array([1.0,2.0,3.0])
a = f > 2.0
print(a)# [False False  True]
print(f[a])# True인 원소만 조회 : [ 3.]

[False False  True]
[ 3.]


In [44]:
# 다차원 배열 조회
f = np.random.rand(3,4)
print(f)
a = f > 0.5
print(a)
print(f[a])

[[ 0.32672592  0.17911634  0.86742821  0.48708593]
 [ 0.09289253  0.45544412  0.41544778  0.95590963]
 [ 0.38140579  0.61071641  0.21484672  0.63228855]]
[[False False  True False]
 [False False False  True]
 [False  True False  True]]
[ 0.86742821  0.95590963  0.61071641  0.63228855]


In [49]:
# 다차원 배열 갱신
data1 = np.random.randn(7,4)
print(data1)
data1[data1 < 0] = 99.0

print(data1)

[[ 0.86446697 -0.92256165  0.66537548  0.87261174]
 [ 0.87445359  0.19634296  0.44228566  1.77255508]
 [ 0.65758845 -1.51219351  0.41865093  0.84553328]
 [-1.50176838 -0.29967465 -0.37142244  0.76319298]
 [-0.00649572 -0.2556     -0.85037455  0.31854527]
 [ 0.4786128  -0.18378067  0.31826275  0.46187732]
 [ 0.76224597 -1.15060416  0.29057682 -1.81522002]]
[[  0.86446697  99.           0.66537548   0.87261174]
 [  0.87445359   0.19634296   0.44228566   1.77255508]
 [  0.65758845  99.           0.41865093   0.84553328]
 [ 99.          99.          99.           0.76319298]
 [ 99.          99.          99.           0.31854527]
 [  0.4786128   99.           0.31826275   0.46187732]
 [  0.76224597  99.           0.29057682  99.        ]]


In [55]:
# Numpy Fancy Indexing
# 원소추출
# 행검색
# 정방향
f = np.arange(0,12).reshape(3,4)
print(f)
print(f[2,0])
print(f[[2,0]])

# 역방향
f = np.arange(0,12).reshape(3,4)
print(f)
print(f[-1,-3])
print(f[[-1,-3]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
8
[[ 8  9 10 11]
 [ 0  1  2  3]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
9
[[ 8  9 10 11]
 [ 0  1  2  3]]


In [65]:
# 순서쌍 처리후 원소만 추출
# 두개의 배열을 주면 첫번째 배열은 행, 두번째 배열은 열로 순서쌍을 구성해서 값 추출
f = np.arange(0,12).reshape(3,4)
print(f)
# (1,0),(2,2)처리 => 4, 10
print(f[[1,2],[0,2]])

B = np.array([[142,56,189,65],
             [299,288,10,12],
             [55,142,17,18]])

# 첫번째 행에 대한 위치조정 후 출력
e0 = np.array([0,0,0,0])
print(e0)
e1 = np.array([0,3,2,1])
print(e1)
f = B[(e0,e1)] #(0,0),(0,3),(0,2),(0,1)

print(f)
           

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 4 10]
[0 0 0 0]
[0 3 2 1]
[142  65 189  56]


In [67]:
# 배열추출
# 첫번째 배열은 행을 처리, 두번째 배열은 열을 처리해서 행과 열로 구성된 배열 추출
f = np.arange(0,12).reshape(3,4)
print(f)
# array 형태로 출력
print(f[[1,2]][:,[0,2]]) # ??

# np.ix_ 함수 이용
f = np.arange(0,12).reshape(3,4)
print(f)

print(f[np.ix_([1,2],[0,2])])# index로 값(배열) 추출

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  6]
 [ 8 10]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  6]
 [ 8 10]]


In [71]:
# 표현식 사용
# 배열에 직접 비교연산 수식을 제공해서 원소 추출
f = np.arange(0,12).reshape(3,4)
print(f)

print(f[f>3].reshape(2,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 8  9 10 11]]


In [74]:
# 표현식 : 산술 + 비교연산
f = np.arange(0,12).reshape(3,4)
print(f)

print(f[f%3 != 0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1  2  4  5  7  8 10 11]


In [75]:
# 메소드 사용
# 배열 내의 원소가 nonzero인 것을 식별하기 위해 nonzero메소드 사용
f = np.arange(0,12).reshape(3,4)
print(f)

print(f[f.nonzero()])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1  2  3  4  5  6  7  8  9 10 11]
